name: Check links

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.22'
      - name: Build
        run: |
          mkdir -p ./app
          cd ./app
          wget https://github.com/tiago123456789/checker-website-links/archive/master.zip
          unzip master.zip
          cd checker-website-links-master
          make build
          ./checker-website-links-linux -api-key '${{ secrets.API_KEY }}' -link https://www.firecrawl.dev/
          cat output.json