name: Check links

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.22'
      - name: Build
        run: |
          make build
          ./checker-website-links -api-key {{ secrets.API_KEY }} -link "https://www.firecrawl.dev/""